### ISSUE TITLE
create project plan

### ISSUE THREAD

**Issue by marco9446** [ASQ-USI/question-editor-asq#3]

**Comment by triglian** [comment]
You can attach it here so that we can review it

**Comment by marco9446** [comment]
[project-plan.zip](https://github.com/ASQ-USI/question-editor-asq/files/151923/project-plan.zip)

**Comment by triglian** [comment]
[ProjectPlan.docx](https://github.com/ASQ-USI/question-editor-asq/files/152891/ProjectPlan.docx)
Please find our comments in the attached folder. Also update the Gantt chart accordingly.

**Comment by marco9446** [comment]
Thank you. i will correct it immediatly

**Comment by marco9446** [comment]
[project_plan_Marco_Ravazzini.pdf](https://github.com/ASQ-USI/question-editor-asq/files/155682/project_plan_Marco_Ravazzini.pdf)

**Comment by triglian** [comment]
I think it looks good.
